openapi: 3.1.0
info:
  title: Course Database API
  version: 1.0.0
  description: API for interacting with MongoDB database for course inform

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /search:
    get:
      summary: Search documents by keyword
      description: Returns a list of documents that match the keyword
      parameters:
        - in: query
          name: keyword
          schema:
            type: string
          required: true
          description: Keyword to search for
        - in: query
          name: modules
          schema:
            type: array
            items:
              type: string
          required: false
          description: List of modules to filter the search
      responses:
        '200':
          description: A list of documents
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/CourseDocument'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '404':
          description: No matching records found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

components:
  schemas:
    CourseDocument:
      type: object
      required:
        - course_name
        - course_url
      properties:
        course_name:
          type: string
          description: Course name
        course_url:
          type: string
          description: Course URL
        video:
          type: array
          items:
            type: object
            properties:
              video_discrption:
                type: string
              video_link1:
                type: string
              video_link2:
                type: string
          description: List of video objects
        files:
          type: array
          items:
            type: object
            properties:
              file_name:
                type: string
              file_url:
                type: string
          description: List of file objects
        assignments:
          type: array
          items:
            type: object
            properties:
              assign_title:
                type: string
              assign_message:
                type: string
              assign_file:
                type: array
                items:
                  type: object
                  properties:
                    file_name:
                      type: string
                    file_url:
                      type: string
          description: List of assignments
        modules:
          type: array
          items:
            type: object
            properties:
              module_name:
                type: string
              attachments:
                type: array
                items:
                  type: object
                  properties:
                    attachment_url:
                      type: string
                    attachment_name:
                      type: string
          description: List of modules
        announcements:
          type: array
          items:
            type: object
            properties:
              ann_title:
                type: string
              ann_message:
                type: string
          description: List of announcements
